// Actions

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';

export const FETCH_QUESTIONS_BY_TOPIC = 'FETCH_QUESTIONS_BY_TOPIC';

export const FETCH_QUESTIONS_BY_TOPIC_SUCCESS = 'FETCH_QUESTIONS_BY_TOPIC_SUCCESS';

export const UPDATE_SELECTED_TOPICS = 'UPDATE_SELECTED_TOPICS';

export const UPDATE_SELECTED_DIFFICULTIES = 'UPDATE_SELECTED_DIFFICULTIES';

export const FETCH_QUESTIONS_BY_DIFFICULTIES = 'FETCH_QUESTIONS_BY_DIFFICULTIES';

export const FETCH_QUESTIONS_BY_DIFFICULTIES_SUCCESS = 'FETCH_QUESTIONS_BY_DIFFICULTIES_SUCCESS';

// Filter Headings

export const EASY = 'Easy'; 

export const MEDIUM = 'Medium'; 

export const HARD = 'Hard'; 